language: generic

env:
  - HOST_UID=1000 HOST_GID=1000

script:
  - bash ./docker-init.sh -c y -p y -m y -e n -n my_nice_acme_project -r 9100
  - cp -R test/build-stubs/* build/web/ && cd build && docker-compose build
  - cd ..
  - bash ./docker-init.sh -c n -p n -m y -e n -n my_nice_acme_project -r 9200
  - cp -R test/build-stubs/* build/web/ && cd build && docker-compose build
  - cd ..
  - bash ./docker-init.sh -c y -p y -m n -e n -n my_nice_acme_project -r 9300
  - cp -R test/build-stubs/* build/web/ && cd build && docker-compose build
  - cd ..
