version: "3"
services:

  web:
    build:
      context: web
      args:
        APP_ENVIRONMENT: 'dev'
    environment:
      CONTAINER_USER: docker
      CONTAINER_GROUP: docker
      HOST_UID: ${HOST_UID}
      HOST_GID: ${HOST_GID}
      PHP_XDEBUG_ENABLED: ${PHP_XDEBUG_ENABLED}
    volumes:
      - ./web/:/var/www/html
      - ./web/data/apache-logs/:/var/log/apache2/
      - ./web/data/symfony-logs/:/var/www/html/var/log/
    ports:
      - ${OUTER_WEBPACK_PORT}:${OUTER_WEBPACK_PORT}

%%MYSQL%%

%%POSTGRES%%

%%ELASTICSEARCH%%
