version: "3"
services:

  web:
    build:
      context: web
      args:
        APP_ENVIRONMENT: 'dev'
    environment:
      APP_ENVIRONMENT: 'dev'
      CONTAINER_USER: docker
      CONTAINER_GROUP: docker
      HOST_UID: ${HOST_UID}
      HOST_GID: ${HOST_GID}
      PHP_XDEBUG_ENABLED: 0
    volumes:
    - .:/var/www/html
#    - ${APACHE_LOG_DIR}:/var/log/apache2/
#    - ${SYMFONY_LOG_DIR}:/var/www/html/var/log/
    ports:
    - ${OUTER_WEB_PORT}:80

%%MYSQL%%

%%POSTGRES%%
