version: "3"
services:

  web:
    build:
      context: web
    environment:
      APP_ENVIRONMENT:
      DEPLOY_ENVIRONMENT:
      CONTAINER_USER: docker
      CONTAINER_GROUP: docker
      HOST_UID: ${HOST_UID}
      HOST_GID: ${HOST_GID}
      PHP_XDEBUG_ENABLED: 0
    volumes:
    - ./web/:/var/www/html
    ports:
    - ${OUTER_WEB_PORT}:443

%%MYSQL%%

%%POSTGRES%%
