version: "3"
services:

  web:
    image: docker-hub.intranet.projektmotor.de/${PROJECT_NAME_HYPHENIZED}-${DEPLOY_ENVIRONMENT}:latest
    ports:
      - "%%OUTER_WEB_PORT_LIVE%%:443"
    volumes:
      - /var/apps/${PROJECT_NAME_HYPHENIZED}-${DEPLOY_ENVIRONMENT}/web/apache-logs/:/var/log/apache2/
      - /var/apps/${PROJECT_NAME_HYPHENIZED}-${DEPLOY_ENVIRONMENT}/web/symfony-logs/:/var/www/html/var/log/
    environment:
      PHP_XDEBUG_ENABLED: 0
      MYSQL_HOST:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:

%%POSTGRES%%
