version: "3"
services:

  web:
    hostname: ${PROJECT_NAME}
    networks:
      - %%PROJECT_NAME_HYPHENIZED%%
    tty: true
    restart: always
    depends_on:
      %%DEPENDS_ON_MYSQL%%
      %%DEPENDS_ON_POSTGRES%%

%%MYSQL%%

%%POSTGRES%%

%%ELASTICSEARCH%%

%%VOLUMES%%
  %%VOLUMES_POSTGRES%%
  %%VOLUMES_ELASTICSEARCH%%

networks:
  %%PROJECT_NAME_HYPHENIZED%%:
    driver: bridge
