##############################################################
# add symfony/panther
##############################################################
RUN apt-get update \&\& apt-get install -y zlib1g-dev unzip chromium \&\& docker-php-ext-install zip
ENV PANTHER_NO_SANDBOX 1
