  mysql:
    image: mysql:5.7
    volumes:
      - /var/apps/${PROJECT_NAME_HYPHENIZED}-${DEPLOY_ENVIRONMENT}/mysql/data/:/var/lib/mysql/
    networks:
      - %%PROJECT_NAME_HYPHENIZED%%
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_PASSWORD:
      MYSQL_DATABASE: %%PROJECT_NAME%%
      MYSQL_USER:  %%PROJECT_NAME%%
